### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by mattip** [uoip/KCFnb#1]
Please add a license file to the repo that describes under what conditions others might use your code. Personally I like the BSD, MIT varieties:

https://opensource.org/licenses/MIT

https://opensource.org/licenses/BSD-2-Clause

https://opensource.org/licenses/BSD-3-Clause

**Comment by uoip** [comment]
Thanks for your advise! I'm not familiar with those open source licenses, but the MIT license seems just fine. Since my code is largely translated from [KCFcpp](https://github.com/joaofaro/KCFcpp) , and I write it just for learning, I'll be happy if it can be useful to others.

**Comment by mattip** [comment]
Thanks, looks good now
